services:
  - type: web
    name: n8n
    plan: free
    dockerImage: n8nio/n8n:latest  # ✅ Correct key
    envVars:
      - fromGroup: n8n-secrets  # ✅ Includes WEBHOOK_URL already
      - key: NODE_ENV
        value: "production"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "5678"
      - key: DB_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_SCHEMA
        value: "public"
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"
      - key: N8N_DISABLE_PRODUCTION_MAIN_MENU
        value: "true"
      - key: N8N_HIDE_UI_FOOTER
        value: "true"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: N8N_AUTH_EXCLUDE_ENDPOINTS
        value: "setup"
      - key: N8N_RUNNERS_ENABLED
        value: "true"
